## 基本概念
* 标量: 一个单独的数, 通常使用斜体小写字母表示，例如$x=1$。


* 向量：可以看作是一个有序的一维数组，通过索引能够唯一的确定向量中的某个值，通常使用斜体加粗的小写字母表示，例如$\boldsymbol{x} = \{1,2,3,4,5 \}$，其中第$i$个元素可以表示为$x_i$。


* 矩阵：矩阵是一个有序的二维数组，其中每个元素由两个索引确定，分别表示它的行和列，通常使用斜体加粗的大写字母表示，例如$\boldsymbol{A} = \left[ \begin{matrix}1 & 2 \\ 3 & 4 \end{matrix} \right]$，一个$n$维向量可以看做是一个$1 \times n$的矩阵。


* 张量：张量表示一个有序的多维数组，其中每个元素可以由多个索引确定，通常使用加粗的大写字母表示，例如$\bf{A}$，向量和矩阵可以分别看作是一维和二维的张量。



In [2]:
import numpy as np
## 生成元素全为0 3x4的张量
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
## 生成三维的随机 张量 2x3x4
np.random.rand(2,3,4)

array([[[0.61327085, 0.63483828, 0.63473814, 0.33253413],
        [0.66045751, 0.18863419, 0.97086113, 0.16469616],
        [0.16194465, 0.13677476, 0.24534555, 0.22521514]],

       [[0.9768769 , 0.36436666, 0.5737545 , 0.06016524],
        [0.00128919, 0.05513583, 0.34653499, 0.47358494],
        [0.55681397, 0.60340053, 0.63688302, 0.19575458]]])

* 方阵: 行数和列数相等的矩阵
* 单位矩阵: 对角线元素为1 其他为零

In [5]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 常用运算
* reshape 改变一个张量的维度和每个维度的大小

In [11]:
x = np.arange(12)
x
x.shape #变成12
x = x.reshape(1,12) 
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [13]:
x.shape
x = x.reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

* 转置 向量和矩阵的转置是交换行列顺序，矩阵$\boldsymbol{A}$的转置记为$\boldsymbol{A}^T$，而三维及以上张量的转置就需要指定转换的维度，示例如下:

In [14]:
x = np.arange(5).reshape(1,-1)
x

array([[0, 1, 2, 3, 4]])

In [15]:
x.T

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [18]:
## 生成3*4的矩阵并转置
A = np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
A.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [21]:
## 2*3*4d的张量
B=np.arange(24).reshape(2,3,4)
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [22]:
B.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

* 矩阵乘法:记两个矩阵分别为A和B,$C=A*B$，则$C_{ij} = \sum_k {A_{i,k}B_{k,j}}$，由公式可以看到两个矩阵能够相乘的条件为第一个矩阵的列数等于第二个矩阵的行数，示例如下：


In [26]:
A=np.arange(6).reshape(3,2)
B=np.arange(6).reshape(2,3)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [27]:
B

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
np.matmul(A,B)

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

* 元素对应运算(Element-wise Operation): 针对形状相同张量的运算统称,包括元素对应乘积,相加等

In [30]:
A=np.arange(6).reshape(3,2)
A*A

array([[ 0,  1],
       [ 4,  9],
       [16, 25]])

In [31]:
A+A

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [32]:
A-A

array([[0, 0],
       [0, 0],
       [0, 0]])

In [34]:
A%A

/Users/code/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in remainder
  """Entry point for launching an IPython kernel.


array([[0, 0],
       [0, 0],
       [0, 0]])

In [35]:
A/A

/Users/code/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

* 逆矩阵: 方阵$\boldsymbol{A}$的逆矩阵记为$\boldsymbol{A}^{-1}$，它满足$\boldsymbol{A*A}^{-1}=\boldsymbol{I}$，示例如下：

In [37]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [38]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

* 特征分解:使用最广的矩阵分解之一,即将矩阵(方阵)分解成一组特征向量与特征值,假设方阵$A$有n个线性无关的特征向量${v_1,v_2,\cdots,v_n}$, 对应着特征值${\lambda_1,\lambda_2,\cdots,\lambda_n}$, 将特征向量连成一个矩阵$V$, 那么$A$的特征分解可以写为$A=Vdiag(\lambda)V^{-1}$.
然而不是每一个矩阵都可以进行特征分解。特别地，每个实对称矩阵都可以分解成实特征向量和实特征值：$A=Qdiag(\lambda)Q^T.$, 其中$Q$是正交矩阵，也就是满足$QQ^T=I$.
在python中，求矩阵的特征值和特征向量实例如下：

In [40]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [41]:
eigvals, eigvectors = np.linalg.eig(A)
eigvals

array([-0.56155281,  3.56155281])

In [42]:
eigvectors

array([[-0.87192821, -0.27032301],
       [ 0.48963374, -0.96276969]])

* 迹运算: 迹运算返回的是方阵对角元素的和 Tr($A$)=$\sum\limits_iA_{ii}$.

迹运算的性质：
1.矩阵转置之后迹保持不变：Tr($A$)=Tr($A^T$).
2.多个矩阵相乘的顺序不改变乘积矩阵的迹（在保持乘积矩阵仍然是方阵情况下），例如假设矩阵$A\in R^{m\times n}$,$B\in R^{n\times m}$,则Tr($A$)=Tr($BA$).
迹运算实例如下：

In [44]:
A=np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [45]:
np.trace(A)

3

* 行列式: 记作det($A$).行列式等于特征值的乘积。行列式的绝对值可以看作是一个n维平行体的体积。实例如下

In [46]:
A=np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [47]:
np.linalg.det(A)

-2.0

* 主成分分析(PCA): 在python中,用sklearn库中的PCA来主成分分析

In [60]:
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris

data=load_iris()
x=data.data
pca=PCA(n_components=2)  #加载PCA算法,设置降维后主成分数目为k
reduced_x=pca.fit_transform(x) #对样本进行降维
ratio=pca.explained_variance_ratio_ #计算各个主成分贡献的方差比例 要求达到80%以上
ratio

array([0.92461872, 0.05306648])